left: ''
right: ''
reader: "opencv"     

width: 2880
height: 1620

display: true
print_fps: true
save_vis: false

sync_dt: 0.8
sync_attempts: 1
cap_buffersize: 1
max_consec_fail: 30

calib_dir: "."
intrinsics: "intrinsics.npz" 

smd:
  night_auto: false
  min_area: 200                

  enable_lr: true              
  lr_use_gradient: false
  lr_subpixel: true
  lr_backtrack_pad: 8
  lr_max_cx_err_px: 2.0

  stereo_max_boxes: 80

 
  stereo_patch: 11
  stereo_search_pad: 48
  stereo_ncc_min: 0.25
  y_eps: 6.0


  y_area_split: 0.65

  persist_k: 4
  persist_m: 2

  log_level: "DEBUG"       # INFO/DEBUG/WARNING
  debug_every_n: 30       